// Code generated by go-swagger; DO NOT EDIT.

package admins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/domdom82/swagger-test/models"
)

// NewAddInventoryParams creates a new AddInventoryParams object
// with the default values initialized.
func NewAddInventoryParams() *AddInventoryParams {
	var ()
	return &AddInventoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAddInventoryParamsWithTimeout creates a new AddInventoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAddInventoryParamsWithTimeout(timeout time.Duration) *AddInventoryParams {
	var ()
	return &AddInventoryParams{

		timeout: timeout,
	}
}

// NewAddInventoryParamsWithContext creates a new AddInventoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewAddInventoryParamsWithContext(ctx context.Context) *AddInventoryParams {
	var ()
	return &AddInventoryParams{

		Context: ctx,
	}
}

// NewAddInventoryParamsWithHTTPClient creates a new AddInventoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAddInventoryParamsWithHTTPClient(client *http.Client) *AddInventoryParams {
	var ()
	return &AddInventoryParams{
		HTTPClient: client,
	}
}

/*AddInventoryParams contains all the parameters to send to the API endpoint
for the add inventory operation typically these are written to a http.Request
*/
type AddInventoryParams struct {

	/*InventoryItem
	  Inventory item to add

	*/
	InventoryItem *models.InventoryItem

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the add inventory params
func (o *AddInventoryParams) WithTimeout(timeout time.Duration) *AddInventoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add inventory params
func (o *AddInventoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add inventory params
func (o *AddInventoryParams) WithContext(ctx context.Context) *AddInventoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add inventory params
func (o *AddInventoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add inventory params
func (o *AddInventoryParams) WithHTTPClient(client *http.Client) *AddInventoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add inventory params
func (o *AddInventoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInventoryItem adds the inventoryItem to the add inventory params
func (o *AddInventoryParams) WithInventoryItem(inventoryItem *models.InventoryItem) *AddInventoryParams {
	o.SetInventoryItem(inventoryItem)
	return o
}

// SetInventoryItem adds the inventoryItem to the add inventory params
func (o *AddInventoryParams) SetInventoryItem(inventoryItem *models.InventoryItem) {
	o.InventoryItem = inventoryItem
}

// WriteToRequest writes these params to a swagger request
func (o *AddInventoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.InventoryItem != nil {
		if err := r.SetBodyParam(o.InventoryItem); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
