// Code generated by go-swagger; DO NOT EDIT.

package developers

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/domdom82/swagger-test/models"
)

// SearchInventoryReader is a Reader for the SearchInventory structure.
type SearchInventoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SearchInventoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewSearchInventoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewSearchInventoryBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSearchInventoryOK creates a SearchInventoryOK with default headers values
func NewSearchInventoryOK() *SearchInventoryOK {
	return &SearchInventoryOK{}
}

/*SearchInventoryOK handles this case with default header values.

search results matching criteria
*/
type SearchInventoryOK struct {
	Payload models.SearchInventoryOKBody
}

func (o *SearchInventoryOK) Error() string {
	return fmt.Sprintf("[GET /inventory][%d] searchInventoryOK  %+v", 200, o.Payload)
}

func (o *SearchInventoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSearchInventoryBadRequest creates a SearchInventoryBadRequest with default headers values
func NewSearchInventoryBadRequest() *SearchInventoryBadRequest {
	return &SearchInventoryBadRequest{}
}

/*SearchInventoryBadRequest handles this case with default header values.

bad input parameter
*/
type SearchInventoryBadRequest struct {
}

func (o *SearchInventoryBadRequest) Error() string {
	return fmt.Sprintf("[GET /inventory][%d] searchInventoryBadRequest ", 400)
}

func (o *SearchInventoryBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
